services:
    bot:
        build: .
        develop:
            watch:
                - action: sync+restart
                  path: .
                  target: /enso-bot
    db:
        build: ./db
        environment:
            - POSTGRES_PASSWORD=postgres
